### ISSUE TITLE
Mixed-up change password menu properties

### ISSUE THREAD

**Issue by LukeAndrews** [Jamf-Custom-Profile-Schemas/mscottblake-schemas#1]
https://github.com/Jamf-Custom-Profile-Schemas/mscottblake-schemas/blob/101bd738913d755b85902c0a5a41c235092487b8/com.trusourcelabs.NoMAD.json#L126

The properties for ChangePasswordOptions and ChangePasswordType are swapped. 

ChangePasswordOptions should have the string input and ChangePasswordType should have the enum of options.

**Comment by MScottBlake** [comment]
Fixed in https://github.com/Jamf-Custom-Profile-Schemas/mscottblake-schemas/commit/1e46b8c7a319bc3109dcbb6516a7aa5949d8adbf
